<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(SOSManagedTargetFramework)</TargetFramework>
    <OutputType>Library</OutputType>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <SelfContained>true</SelfContained>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <InvariantGlobalization>true</InvariantGlobalization>
    <IlcTreatWarningsAsErrors>false</IlcTreatWarningsAsErrors>
    <ILLinkTreatWarningsAsErrors>false</ILLinkTreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
    <IsShipping>false</IsShipping>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(MSBuildThisFileDirectory)..\SOS.Extensions\SOS.Extensions.csproj" />
    <TrimmerRootAssembly Include="SOS.Extensions" />
  </ItemGroup>
</Project>
