// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using Microsoft.Diagnostics.DebugServices;
using SOS.Hosting.Interop;

namespace SOS.Hosting
{
    [GeneratedComClass]
    public sealed partial class SymbolServiceWrapper : ISymbolServiceGenerated
    {
        /// <summary>
        /// Matches the IRuntime::RuntimeConfiguration in runtime.h
        /// </summary>
        public enum RuntimeConfiguration
        {
            WindowsDesktop = 0,
            WindowsCore = 1,
            UnixCore = 2,
            OSXCore = 3
        }

        private readonly ISymbolService _symbolService;
        private readonly IMemoryService _memoryService;
        private readonly ulong _ignoreAddressBitsMask;

        public SymbolServiceWrapper(ISymbolService symbolService, IMemoryService memoryService)
        {
            Debug.Assert(symbolService != null);
            Debug.Assert(memoryService != null);
            _symbolService = symbolService;
            _memoryService = memoryService;
            _ignoreAddressBitsMask = memoryService.SignExtensionMask();
        }

        /// <summary>
        /// Parse the Windows sympath format
        /// </summary>
        /// <param name="symbolPath">windows symbol path</param>
        /// <returns>if false, failure</returns>
        bool ISymbolServiceGenerated.ParseSymbolPath(string symbolPath)
        {
            if (string.IsNullOrWhiteSpace(symbolPath))
            {
                return false;
            }
            _symbolService.DisableSymbolStore();
            return _symbolService.ParseSymbolPathFixDefault(symbolPath);
        }

        /// <summary>
        /// Get expression helper for native SOS.
        /// </summary>
        /// <param name="expression">hex number</param>
        /// <returns>value</returns>
        ulong ISymbolServiceGenerated.GetExpressionValue(string expression)
        {
            if (expression != null)
            {
                if (ulong.TryParse(expression.Replace("0x", ""), NumberStyles.HexNumber, CultureInfo.InvariantCulture, out ulong result))
                {
                    return result;
                }
            }
            return 0;
        }

        /// <summary>
        /// Checks availability of debugging information for given assembly.
        /// </summary>
        /// <param name="assemblyPath">
        /// File path of the assembly or null
        /// </param>
        /// <param name="isFileLayout">type of in-memory PE layout, if true, file based layout otherwise, loaded layout</param>
        /// <param name="loadedPeAddress">
        /// Loaded PE image address or zero if the module is dynamic (generated by Reflection.Emit).
        /// Dynamic modules have their PDBs (if any) generated to an in-memory stream
        /// (pointed to by <paramref name="inMemoryPdbAddress"/> and <paramref name="inMemoryPdbSize"/>).
        /// </param>
        /// <param name="loadedPeSize">loaded PE image size</param>
        /// <param name="inMemoryPdbAddress">in memory PDB address or zero</param>
        /// <param name="inMemoryPdbSize">in memory PDB size</param>
        /// <returns>Symbol reader handle or zero if error</returns>
        IntPtr ISymbolServiceGenerated.LoadSymbolsForModule(
            string assemblyPath,
            bool isFileLayout,
            ulong loadedPeAddress,
            uint loadedPeSize,
            ulong inMemoryPdbAddress,
            uint inMemoryPdbSize)
        {
            try
            {
                ISymbolFile symbolFile = null;
                if (loadedPeAddress != 0)
                {
                    loadedPeAddress &= _ignoreAddressBitsMask;
                    Stream peStream = _memoryService.CreateMemoryStream(loadedPeAddress, loadedPeSize);
                    symbolFile = _symbolService.OpenSymbolFile(assemblyPath, isFileLayout, peStream);
                }
                if (inMemoryPdbAddress != 0)
                {
                    inMemoryPdbAddress &= _ignoreAddressBitsMask;
                    Stream pdbStream = _memoryService.CreateMemoryStream(inMemoryPdbAddress, inMemoryPdbSize);
                    symbolFile = _symbolService.OpenSymbolFile(pdbStream);
                }
                if (symbolFile != null)
                {
                    GCHandle gch = GCHandle.Alloc(symbolFile);
                    return GCHandle.ToIntPtr(gch);
                }
            }
            catch (Exception ex)
            {
                Trace.TraceError($"LoadSymbolsForModule: {ex.Message}");
            }
            return IntPtr.Zero;
        }

        /// <summary>
        /// Cleanup and dispose of symbol reader handle
        /// </summary>
        /// <param name="symbolReaderHandle">symbol reader handle returned by LoadSymbolsForModule</param>
        void ISymbolServiceGenerated.Dispose(IntPtr symbolReaderHandle)
        {
            Debug.Assert(symbolReaderHandle != IntPtr.Zero);
            try
            {
                GCHandle gch = GCHandle.FromIntPtr(symbolReaderHandle);
                if (gch.Target is IDisposable disposable)
                {
                    disposable.Dispose();
                }
                gch.Free();
            }
            catch (Exception ex)
            {
                Trace.TraceError($"Dispose: {ex.Message}");
            }
        }

        /// <summary>
        /// Returns method token and IL offset for given source line number.
        /// </summary>
        /// <param name="symbolReaderHandle">symbol reader handle returned by LoadSymbolsForModule</param>
        /// <param name="filePath">source file name and path</param>
        /// <param name="lineNumber">source line number</param>
        /// <param name="methodToken">method token return</param>
        /// <param name="ilOffset">IL offset return</param>
        /// <returns> true if information is available</returns>
        bool ISymbolServiceGenerated.ResolveSequencePoint(
            IntPtr symbolReaderHandle,
            string filePath,
            int lineNumber,
            out int methodToken,
            out int ilOffset)
        {
            Debug.Assert(symbolReaderHandle != IntPtr.Zero);
            GCHandle gch = GCHandle.FromIntPtr(symbolReaderHandle);
            ISymbolFile symbolFile = (ISymbolFile)gch.Target;
            return symbolFile.ResolveSequencePoint(filePath, lineNumber, out methodToken, out ilOffset);
        }

        /// <summary>
        /// Returns source line number and source file name for given IL offset and method token.
        /// </summary>
        /// <param name="symbolReaderHandle">symbol reader handle returned by LoadSymbolsForModule</param>
        /// <param name="methodToken">method token</param>
        /// <param name="ilOffset">IL offset</param>
        /// <param name="lineNumber">source line number return</param>
        /// <param name="fileName">source file name return</param>
        /// <returns> true if information is available</returns>
        bool ISymbolServiceGenerated.GetLineByILOffset(
            IntPtr symbolReaderHandle,
            int methodToken,
            long ilOffset,
            out int lineNumber,
            out string fileName)
        {
            Debug.Assert(symbolReaderHandle != IntPtr.Zero);
            fileName = null;

            GCHandle gch = GCHandle.FromIntPtr(symbolReaderHandle);
            ISymbolFile symbolFile = (ISymbolFile)gch.Target;
            if (!symbolFile.GetSourceLineByILOffset(methodToken, ilOffset, out lineNumber, out string sourceFileName))
            {
                return false;
            }
            fileName = sourceFileName;
            return true;
        }

        /// <summary>
        /// Returns local variable name for given local index and IL offset.
        /// </summary>
        /// <param name="symbolReaderHandle">symbol reader handle returned by LoadSymbolsForModule</param>
        /// <param name="methodToken">method token</param>
        /// <param name="localIndex">local variable index</param>
        /// <param name="localVarName">local variable name return</param>
        /// <returns>true if name has been found</returns>
        bool ISymbolServiceGenerated.GetLocalVariableName(
            IntPtr symbolReaderHandle,
            int methodToken,
            int localIndex,
            out string localVarName)
        {
            Debug.Assert(symbolReaderHandle != IntPtr.Zero);
            localVarName = null;

            GCHandle gch = GCHandle.FromIntPtr(symbolReaderHandle);
            ISymbolFile symbolFile = (ISymbolFile)gch.Target;
            if (!symbolFile.GetLocalVariableByIndex(methodToken, localIndex, out string localVar))
            {
                return false;
            }
            localVarName = localVar;
            return true;
        }

        /// <summary>
        /// Metadata locator helper for the DAC.
        /// </summary>
        /// <param name="imagePath">file name and path to module</param>
        /// <param name="imageTimestamp">module timestamp</param>
        /// <param name="imageSize">module image</param>
        /// <param name="mvid">not used</param>
        /// <param name="mdRva">not used</param>
        /// <param name="flags">not used</param>
        /// <param name="bufferSize">size of incoming buffer (pMetadata)</param>
        /// <param name="pMetadata">pointer to buffer</param>
        /// <param name="pMetadataSize">size of outgoing metadata</param>
        /// <returns>HRESULT</returns>
        int ISymbolServiceGenerated.GetMetadataLocator(
            string imagePath,
            uint imageTimestamp,
            uint imageSize,
            byte[] mvid,
            uint mdRva,
            uint flags,
            uint bufferSize,
            IntPtr pMetadata,
            IntPtr pMetadataSize)
        {
            return _symbolService.GetMetadataLocator(
                imagePath,
                imageTimestamp,
                imageSize,
                mvid,
                mdRva,
                flags,
                bufferSize,
                pMetadata,
                pMetadataSize);
        }

        /// <summary>
        /// Metadata locator helper for the DAC.
        /// </summary>
        /// <param name="imagePath">file name and path to module</param>
        /// <param name="imageTimestamp">module timestamp</param>
        /// <param name="imageSize">module image</param>
        /// <param name="pathBufferSize">output buffer size</param>
        /// <param name="pPathBufferSize">native pointer to put actual path size</param>
        /// <param name="pwszPathBuffer">native pointer to WCHAR path buffer</param>
        /// <returns>HRESULT</returns>
        int ISymbolServiceGenerated.GetICorDebugMetadataLocator(
            string imagePath,
            uint imageTimestamp,
            uint imageSize,
            uint pathBufferSize,
            IntPtr pPathBufferSize,
            IntPtr pwszPathBuffer)
        {
            return _symbolService.GetICorDebugMetadataLocator(
                imagePath,
                imageTimestamp,
                imageSize,
                pathBufferSize,
                pPathBufferSize,
                pwszPathBuffer);
        }
    }
}
